### ISSUE TITLE
Bài 11. Deploy web app lên nhưng không chạy

### ISSUE THREAD

**Issue by lekien-2803** [lekien-2803/docker-swarm-practice#2]
## 1. Mục tiêu
Kết nối Golang app với database postgres, ứng dụng Golang app truy vấn bảng people bằng câu lệnh `SELECT * FROM people` rồi trả về JSON ở cổng 8088.

## 2. Thực hiện
Làm [bài tập 11](https://github.com/lekien-2803/docker-swarm-practice/tree/main/11-docker-registry) với các file docker-compose.yml, main.go như sau:

docker-compose.yml:
```yaml
version: '3.3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123-
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-overlay

  app:
    image: my-golang-app
    ports:
      - "8088:8080"
    depends_on:
      - postgres
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.myapp.rule=Host(`myapp.com`)"
        - "traefik.http.services.myapp.loadbalancer.server.port=8088"
      replicas: 1      
    networks:
      - my-overlay

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    networks:
      - my-overlay

volumes:
  postgres_data:

networks:
  my-overlay:
    driver: overlay
```

main.go:
```go
package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"

	_ "github.com/lib/pq"
)

type Person struct {
    ID         int    `json:"id"`
    FirstName  string `json:"first_name"`
    LastName   string `json:"last_name"`
    Gender     string `json:"gender"`
    DateOfBirth string `json:"date_of_birth"`
}

func main() {
    
    // Đọc mật khẩu từ biến môi trường
    password := os.Getenv("POSTGRES_PASSWORD")

    // Kiểm tra xem mật khẩu đã được đặt hay chưa
    if password == "" {
        log.Fatal("Missing POSTGRES_PASSWORD environment variable")
    }

    // Tạo chuỗi kết nối với mật khẩu
    connStr := fmt.Sprintf("user=root dbname=demo sslmode=disable host=postgres password=%s", password)
    


    db, err := sql.Open("postgres", connStr)
    if err != nil {
        log.Fatal(err)
    }

    http.HandleFunc("/people", func(w http.ResponseWriter, r *http.Request) {
        rows, err := db.Query("SELECT * FROM people")
        if err != nil {
            http.Error(w, err.Error(), http.StatusInternalServerError)
            return
        }
        defer rows.Close()

        var people []Person
        for rows.Next() {
            var p Person
            if err := rows.Scan(&p.ID, &p.FirstName, &p.LastName, &p.Gender, &p.DateOfBirth); err != nil {
                http.Error(w, err.Error(), http.StatusInternalServerError)
                return
            }
            people = append(people, p)
        }

        w.Header().Set("Content-Type", "application/json")
        json.NewEncoder(w).Encode(people)
    })

    log.Fatal(http.ListenAndServe(":8088", nil))
}
```

### 3.1. Service của app golang không chạy, không có một replica nào:
![image](https://github.com/lekien-2803/docker-swarm-practice/assets/144997507/54db47c9-908b-4c51-b72b-0fa5e7b05b09)

Kiểm tra trên cluster visualizer thì thấy liên tục bị rejected hoặc failed:
![image](https://github.com/lekien-2803/docker-swarm-practice/assets/144997507/c902368e-d527-437d-bef1-d16a49cdc0ad)

Sevice logs ghi:
![image](https://github.com/lekien-2803/docker-swarm-practice/assets/144997507/b5a2644d-a4d9-479d-9557-379a24e72f23)

### 3.2. Không truy cập được vào web app golang thông qua cổng 8088 đã cấu hình

Sử dụng đường dẫn tới cổng 8081, tức là adminer thì vẫn vào được bình thường:
![image](https://github.com/lekien-2803/docker-swarm-practice/assets/144997507/3e8d4df1-9fe4-4e59-b18c-713c4464e89f)

Tuy nhiên web app golang lại không chạy khi mở trên cổng 8088:
![image](https://github.com/lekien-2803/docker-swarm-practice/assets/144997507/2ab27d30-a839-47b5-8018-abfe80c8dfeb)

#### 4.1.1. Nguyên nhân
Biến môi trường POSTGRES_PASSWORD không có sẵn trong service `app` nên không thể lấy ra được password.
#### 4.1.2. Khắc phục

Thêm biến môi trường vào service app trong `docker-compose.yml`:
```yaml
version: '3.3'
services:
...
  app:
    ...
    environment:
      POSTGRES_PASSWORD: abc123-   
               # Thêm biến môi trường POSTGRES_PASSWORD để go có thể bắt được mật khẩu của postgres
...
```
#### 4.1.3. Kết quả
      
![image](https://github.com/lekien-2803/docker-swarm-practice/assets/144997507/e1b1d319-623c-444d-8ea2-7a435a885a3d)

![image](https://github.com/lekien-2803/docker-swarm-practice/assets/144997507/c88a0224-ab00-4112-836f-c1b902eba547)

#### 4.2.1. Nguyên nhân
Trong mã nguồn Go, ứng dụng đang lắng nghe trên cổng `8088`. Trong Docker, khi bạn map cổng, cú pháp là `PORT_HOST:PORT_CONTAINER`. Trong trường hợp của bạn, cổng `PORT_CONTAINER` là cổng mà ứng dụng bên trong container đang lắng nghe, tức là cổng `8088` theo mã nguồn Go.

#### 4.2.2. Khắc phục
Sửa lại trong file `docker-compose.yml` như sau:
```yaml
version: '3.3'
services:
  # Các cài đặt khác giữ nguyên
  app:
    image: 192.168.56.101:5000/go-app
    ports:
      - "8088:8088" #sửa lại cổng 

    # Các cài đặt khác giữ nguyên
```
#### 4.2.3. Kết quả
![image](https://github.com/lekien-2803/docker-swarm-practice/assets/144997507/37c4a2cc-820c-4bc1-bea6-388cea30b12b)
